#
# Copyright (c) Microsoft Corporation.   All rights reserved.
#

!if "$(ROOT)" == ""
ROOT = ..
!endif

NAMESPACE = Bartok.DebugInfo

SUB_DIRS =

LIB_FILES = \
    $(SRCDIR)\DebugInfo.cs  

LIB_IMPORTS =

LIB_CSCFLAGS =

!include $(ROOT)\build\makefile.library



